In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = []

for num in arr:
    result.append(num ** 2)

print(result)

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


In [2]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2
print(result)

[ 1  4  9 16 25]


In [3]:
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10
print(result)

[11 12 13 14 15]


In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

result = arr1 + arr2
print(result)

[11 22 33]
