In [1]:
import numpy as np
arr = np.array([[1, 2, 3],[4,5,6],[7, 8, 9],[10, 11, 12]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
flat[0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
flat[ : 13]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
flat[5:6]

array([6])

In [9]:
flat[5:7]

array([6, 7])

In [10]:
flat[0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
flat[::5]

array([ 1,  6, 11])

In [23]:
flat

array([ 0,  2,  3,  0,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
b = flat[3 : 7].copy()

In [30]:
b

array([55555,     5,     6,     7])

In [27]:
b[0] = 55555

In [28]:
b

array([55555,     5,     6,     7])

In [29]:
flat


array([    0,     2,     3, 55555,     5,     6,     7,     8,     9,
          10,    11,    12])

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [33]:
arr[[1, 4, 6]]

array([2, 5, 7])

In [35]:
arr[arr > 5]

array([6, 7, 8, 9])

In [37]:
 arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [38]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr.shape

(3, 3)