In [1]:
import numpy as np np.

In [2]:
arr = np.array([3, 5, 2, 33])

In [3]:
np.mean(arr)

np.float64(10.75)

In [4]:
np.max(arr)

np.int64(33)

In [5]:
np.min(arr)

np.int64(2)

In [6]:
np.std(arr)

np.float64(12.891373084353738)

In [7]:
np.var(arr)

np.float64(166.1875)

In [11]:
np.percentile(arr, 50)

np.float64(4.0)

In [12]:
np.diff(arr)

array([ 2, -3, 31])

In [13]:
np.unique(arr)

array([ 2,  3,  5, 33])

In [14]:
np.exp(arr)

array([2.00855369e+01, 1.48413159e+02, 7.38905610e+00, 2.14643580e+14])