In [1]:
import numpy as np
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr[0]

array([1, 2, 3])

In [4]:
arr[1]

array([4, 5, 6])

In [5]:
np.sum(arr, axis = 0)

array([12, 15, 18])

In [9]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])